const sessionManager = require("./sessionManager");

const VISUALIZATIONS = {
    bubble: {
        name: "Bubble Sort (C)",
        file: "bubble.c",
        code: [
            "#include <stdio.h>",
            "#include <stdlib.h>",
            "#include <unistd.h>",
            "",
            "#define SIZE 10",
            "#define DELAY 150000",
            "",
            "void print_array(int arr[], int size, int active1, int active2) {",
            '    puts("Visualizing Bubble Sort (C)");',
            '    puts("--------------------------------");',
            "    for (int i = 0; i < size; i++) {",
            '        for (int j = 0; j < arr[i]; j++) printf("#");',
            '        printf(" (%d)", arr[i]);',
            '        if (i == active1 || i == active2) printf(" <--");',
            '        puts("");',
            "    }",
            '    puts("");',
            "    fflush(stdout);",
            "}",
            "",
            "int main() {",
            "    int arr[SIZE] = {9, 3, 5, 1, 8, 2, 7, 4, 10, 6};",
            "    for (int i = 0; i < SIZE - 1; i++) {",
            "        for (int j = 0; j < SIZE - i - 1; j++) {",
            "            print_array(arr, SIZE, j, j + 1);",
            "            usleep(DELAY);",
            "            if (arr[j] > arr[j + 1]) {",
            "                int temp = arr[j];",
            "                arr[j] = arr[j + 1];",
            "                arr[j + 1] = temp;",
            "                print_array(arr, SIZE, j, j + 1);",
            "                usleep(DELAY);",
            "            }",
            "        }",
            "    }",
            "    print_array(arr, SIZE, -1, -1);",
            "    return 0;",
            "}",
        ].join("\n"),
    },
    selection: {
        name: "Selection Sort (C)",
        file: "selection.c",
        code: [
            "#include <stdio.h>",
            "#include <stdlib.h>",
            "#include <unistd.h>",
            "",
            "#define SIZE 10",
            "#define DELAY 200000",
            "",
            "void print_array(int arr[], int size, int min_idx, int current) {",
            '    puts("Visualizing Selection Sort (C)");',
            '    puts("--------------------------------");',
            "    for (int i = 0; i < size; i++) {",
            '        for (int j = 0; j < arr[i]; j++) printf("#");',
            '        printf(" (%d)", arr[i]);',
            '        if (i == min_idx) printf(" <-- [MIN]");',
            '        else if (i == current) printf(" <-- [SCAN]");',
            '        puts("");',
            "    }",
            '    puts("");',
            "    fflush(stdout);",
            "}",
            "",
            "int main() {",
            "    int arr[SIZE] = {7, 2, 9, 1, 5, 10, 4, 3, 8, 6};",
            "    for (int i = 0; i < SIZE - 1; i++) {",
            "        int min_idx = i;",
            "        for (int j = i + 1; j < SIZE; j++) {",
            "            print_array(arr, SIZE, min_idx, j);",
            "            usleep(DELAY);",
            "            if (arr[j] < arr[min_idx]) min_idx = j;",
            "        }",
            "        int temp = arr[min_idx];",
            "        arr[min_idx] = arr[i];",
            "        arr[i] = temp;",
            "    }",
            "    print_array(arr, SIZE, -1, -1);",
            "    return 0;",
            "}",
        ].join("\n"),
    },
    quick: {
        name: "Quick Sort (C)",
        file: "quick.c",
        code: [
            "#include <stdio.h>",
            "#include <stdlib.h>",
            "#include <unistd.h>",
            "",
            "#define SIZE 10",
            "#define DELAY 250000",
            "",
            "void print_array(int arr[], int size, int p, int low, int high) {",
            '    puts("Visualizing Quick Sort (C)");',
            '    puts("--------------------------------");',
            "    for (int i = 0; i < size; i++) {",
            '        for (int j = 0; j < arr[i]; j++) printf("#");',
            '        printf(" (%d)", arr[i]);',
            '        if (i == p) printf(" <-- [PIVOT]");',
            '        else if (i >= low && i <= high) printf(" <--");',
            '        puts("");',
            "    }",
            '    puts("");',
            "    fflush(stdout);",
            "}",
            "",
            "int partition(int arr[], int low, int high, int size) {",
            "    int pivot = arr[high];",
            "    int i = (low - 1);",
            "    for (int j = low; j <= high - 1; j++) {",
            "        print_array(arr, size, high, i+1, j);",
            "        usleep(DELAY);",
            "        if (arr[j] < pivot) {",
            "            i++;",
            "            int t = arr[i]; arr[i] = arr[j]; arr[j] = t;",
            "        }",
            "    }",
            "    int t = arr[i + 1]; arr[i + 1] = arr[high]; arr[high] = t;",
            "    return (i + 1);",
            "}",
            "",
            "void quickSort(int arr[], int low, int high, int size) {",
            "    if (low < high) {",
            "        int pi = partition(arr, low, high, size);",
            "        quickSort(arr, low, pi - 1, size);",
            "        quickSort(arr, pi + 1, high, size);",
            "    }",
            "}",
            "",
            "int main() {",
            "    int arr[SIZE] = {10, 7, 8, 9, 1, 5, 2, 4, 3, 6};",
            "    quickSort(arr, 0, SIZE - 1, SIZE);",
            "    print_array(arr, SIZE, -1, -1, -1);",
            "    return 0;",
            "}",
        ].join("\n"),
    },
    pathfinder: {
        name: "BFS Pathfinding (C)",
        file: "pathfinder.c",
        code: [
            "#include <stdio.h>",
            "#include <stdlib.h>",
            "#include <unistd.h>",
            "",
            "#define ROWS 7",
            "#define COLS 15",
            "#define DELAY 55000",
            "",
            "char grid[ROWS][COLS];",
            "int visited[ROWS][COLS];",
            "",
            "void print_grid() {",
            '    puts("Visualizing BFS Pathfinding (C)");',
            '    puts("--------------------------------");',
            "    for (int i = 0; i < ROWS; i++) {",
            "        for (int j = 0; j < COLS; j++) {",
            '            printf("%c ", grid[i][j]);',
            "        }",
            '        puts("");',
            "    }",
            '    puts("");',
            "    fflush(stdout);",
            "}",
            "",
            "int main() {",
            "    // Initialize grid",
            "    for(int i=0; i<ROWS; i++) for(int j=0; j<COLS; j++) { grid[i][j] = '.'; visited[i][j] = 0; }",
            "    ",
            "    int startR = 3, startC = 2;",
            "    int endR = 3, endC = 12;",
            "    grid[startR][startC] = 'S';",
            "    grid[endR][endC] = 'E';",
            "    ",
            "    // BFS Queue simulation",
            "    int qR[100], qC[100];",
            "    int head=0, tail=0;",
            "    ",
            "    qR[tail] = startR; qC[tail] = startC; tail++;",
            "    visited[startR][startC] = 1;",
            "    ",
            "    int dr[] = {-1, 1, 0, 0};",
            "    int dc[] = {0, 0, -1, 1};",
            "    ",
            "    while(head < tail) {",
            "        int r = qR[head]; int c = qC[head]; head++;",
            "        ",
            "        if (r == endR && c == endC) break;",
            "        ",
            "        if (grid[r][c] == '.') grid[r][c] = '*';",
            "        ",
            "        print_grid();",
            "        usleep(DELAY);",
            "        ",
            "        for(int i=0; i<4; i++) {",
            "            int nr = r + dr[i]; int nc = c + dc[i];",
            "            if(nr >= 0 && nr < ROWS && nc >= 0 && nc < COLS && !visited[nr][nc]) {",
            "                visited[nr][nc] = 1;",
            "                qR[tail] = nr; qC[tail] = nc; tail++;",
            "            }",
            "        }",
            "    }",
            "    ",
            "    return 0;",
            "}",
        ].join("\n"),
    },
    dfs: {
        name: "DFS Pathfinding (C)",
        file: "dfs.c",
        code: [
            "#include <stdio.h>",
            "#include <stdlib.h>",
            "#include <unistd.h>",
            "",
            "#define ROWS 7",
            "#define COLS 15",
            "#define DELAY 55000",
            "",
            "char grid[ROWS][COLS];",
            "int visited[ROWS][COLS];",
            "int endR = 3, endC = 12;",
            "",
            "void print_grid() {",
            '    puts("Visualizing DFS Pathfinding (C)");',
            '    puts("--------------------------------");',
            "    for (int i = 0; i < ROWS; i++) {",
            '        for (int j = 0; j < COLS; j++) printf("%c ", grid[i][j]);',
            '        puts("");',
            "    }",
            '    puts("");',
            "    fflush(stdout);",
            "}",
            "",
            "int solve(int r, int c) {",
            "    if (r < 0 || r >= ROWS || c < 0 || c >= COLS || visited[r][c]) return 0;",
            "    if (r == endR && c == endC) return 1;",
            "    ",
            "    visited[r][c] = 1;",
            "    if (grid[r][c] == '.') grid[r][c] = '*';",
            "    print_grid();",
            "    usleep(DELAY);",
            "    ",
            "    // Up, Down, Left, Right",
            "    if (solve(r-1, c)) return 1;",
            "    if (solve(r+1, c)) return 1;",
            "    if (solve(r, c-1)) return 1;",
            "    if (solve(r, c+1)) return 1;",
            "    ",
            "    return 0;",
            "}",
            "",
            "int main() {",
            "    for(int i=0; i<ROWS; i++) for(int j=0; j<COLS; j++) { grid[i][j] = '.'; visited[i][j] = 0; }",
            "    grid[3][2] = 'S'; grid[endR][endC] = 'E';",
            "    solve(3, 2);",
            "    return 0;",
            "}",
        ].join("\n"),
    },
    life: {
        name: "Conway's Game of Life (Python)",
        file: "life_app.py",
        language: "python",
        code: [
            "import time, random, sys",
            "",
            "ROWS, COLS, DELAY, GENS = 16, 36, 0.20, 45",
            "random.seed(42)",
            "",
            "def count_n(g, r, c):",
            "    return sum(g[(r+dr)%ROWS][(c+dc)%COLS]",
            "               for dr in (-1,0,1) for dc in (-1,0,1) if (dr,dc)!=(0,0))",
            "",
            "def next_gen(g):",
            "    n = [[False]*COLS for _ in range(ROWS)]",
            "    for r in range(ROWS):",
            "        for c in range(COLS):",
            "            k = count_n(g, r, c)",
            "            n[r][c] = (k==3) if not g[r][c] else (k in (2,3))",
            "    return n",
            "",
            "g = [[random.random()<0.32 for _ in range(COLS)] for _ in range(ROWS)]",
            "for gen in range(GENS+1):",
            "    alive = sum(c for row in g for c in row)",
            "    lines = [",
            '        "Conway\'s Game of Life  (Python)",',
            '        "Rule B3/S23:  Born=3 neighbors  |  Survive=2-3",',
            '        "Gen: {:3d}  Alive: {:3d}".format(gen, alive),',
            '        "+" + "-"*COLS + "+",',
            "    ]",
            "    for row in g:",
            '        lines.append("|"+"".join("#" if c else " " for c in row)+"|")',
            '    lines.append("+" + "-"*COLS + "+")',
            '    sys.stdout.write("\\n".join(lines)+"\\n")',
            "    sys.stdout.flush()",
            "    if gen < GENS:",
            "        time.sleep(DELAY)",
            "        g = next_gen(g)",
        ].join("\n"),
    },
    mandelbrot: {
        name: "Mandelbrot Set (Python)",
        file: "mandelbrot_app.py",
        language: "python",
        code: [
            "import sys, time",
            "",
            "W, H = 54, 20",
            'CHARS = "  .,:;!|?%#@"',
            "STEPS = [2, 3, 4, 5, 7, 9, 12, 16, 21, 28, 37, 49, 65, 80, 100, 130]",
            "",
            "def render(max_iter, i, total):",
            "    lines = [",
            '        "Mandelbrot Set  (Python)",',
            '        "Increasing depth reveals infinite boundary detail",',
            '        "Depth: {:3d}   Frame: {}/{}".format(max_iter, i+1, total),',
            '        "+" + "-"*W + "+",',
            "    ]",
            "    for py in range(H):",
            '        row = ""',
            "        for px in range(W):",
            "            cr = (px/W)*3.5 - 2.5",
            "            ci = (py/H)*2.0 - 1.0",
            "            zr, zi, n = 0.0, 0.0, 0",
            "            while zr*zr+zi*zi < 4 and n < max_iter:",
            "                zr, zi = zr*zr-zi*zi+cr, 2*zr*zi+ci",
            "                n += 1",
            "            row += CHARS[n % len(CHARS)]",
            '        lines.append("|"+row+"|")',
            '    lines.append("+" + "-"*W + "+")',
            '    sys.stdout.write("\\n".join(lines)+"\\n")',
            "    sys.stdout.flush()",
            "",
            "for i, d in enumerate(STEPS):",
            "    render(d, i, len(STEPS))",
            "    time.sleep(0.25)",
        ].join("\n"),
    },
    montecarlo: {
        name: "Monte Carlo PI (Python)",
        file: "montecarlo_app.py",
        language: "python",
        code: [
            "import random, sys, time, math",
            "",
            "random.seed(123)",
            "W, H = 38, 19",
            "BATCHES, PER = 25, 150",
            "total = inside = 0",
            'vis = [["." for _ in range(W)] for _ in range(H)]',
            "",
            "for b in range(BATCHES):",
            "    for _ in range(PER):",
            "        x, y = random.uniform(-1,1), random.uniform(-1,1)",
            "        gx = min(W-1, int((x+1)/2*W))",
            "        gy = min(H-1, int((y+1)/2*H))",
            "        if x*x+y*y <= 1.0:",
            "            inside += 1",
            '            vis[gy][gx] = "o"',
            "        else:",
            '            vis[gy][gx] = "x"',
            "        total += 1",
            "    pi = 4.0*inside/total",
            "    err = abs(pi-math.pi)/math.pi*100",
            "    bar = int(28*inside/total)",
            "    lines = [",
            '        "Monte Carlo PI Estimation  (Python)",',
            '        "Drop random points; ratio inside circle -> PI/4",',
            '        "o=inside circle  x=outside  formula: 4*(in/total)",',
            '        "Samples: {:5d}  Est: {:.6f}  Err: {:.4f}%".format(total,pi,err),',
            '        "[" + "="*bar + ">"+ " "*(28-bar) + "] converging to pi",',
            '        "+" + "-"*W + "+",',
            "    ]",
            '    for row in vis: lines.append("|"+"".join(row)+"|")',
            '    lines.append("+" + "-"*W + "+")',
            '    sys.stdout.write("\\n".join(lines)+"\\n")',
            "    sys.stdout.flush()",
            "    time.sleep(0.15)",
            "",
            "pi_final = 4.0*inside/total",
            "err_final = abs(pi_final-math.pi)/math.pi*100",
            "time.sleep(0.3)",
            "sys.stdout.write(",
            "    '\\n  ══════════════════════════════════════\\n'",
            "    f'  Final estimate:  π ≈ {pi_final:.8f}\\n'",
            "    f'  True π:          {math.pi:.8f}\\n'",
            "    f'  Error:           {err_final:.6f}%\\n'",
            "    f'  Samples used:    {total}\\n'",
            "    '  ══════════════════════════════════════\\n'",
            ")",
            "sys.stdout.flush()",
            "time.sleep(0.5)",
        ].join("\n"),
    },
    maze: {
        name: "Maze Generator + Solver (Python)",
        file: "maze_app.py",
        language: "python",
        code: [
            "import random, sys, time, collections",
            "",
            "sys.setrecursionlimit(5000)",
            "random.seed(99)",
            "ROWS, COLS = 8, 15",
            "GH, GW = 2*ROWS+1, 2*COLS+1",
            'g = [["#"]*GW for _ in range(GH)]',
            "vis = [[False]*COLS for _ in range(ROWS)]",
            "for r in range(ROWS):",
            '    for c in range(COLS): g[2*r+1][2*c+1] = " "',
            "",
            "def draw(stage):",
            '    lines = ["Maze Generator + Solver  (Python)", stage,',
            '             "+" + "-"*GW + "+"]',
            '    for row in g: lines.append("|"+"".join(row)+"|")',
            '    lines.append("+" + "-"*GW + "+")',
            '    sys.stdout.write("\\n".join(lines)+"\\n")',
            "    sys.stdout.flush()",
            "",
            "step = [0]",
            "def gen(r, c):",
            "    vis[r][c] = True",
            "    dirs = [(0,1),(0,-1),(1,0),(-1,0)]",
            "    random.shuffle(dirs)",
            "    for dr, dc in dirs:",
            "        nr, nc = r+dr, c+dc",
            "        if 0<=nr<ROWS and 0<=nc<COLS and not vis[nr][nc]:",
            '            g[r+nr+1][c+nc+1] = " "',
            "            step[0] += 1",
            "            if step[0] % 3 == 0:",
            '                g[2*r+1][2*c+1] = "G"',
            '                draw("Generating maze  (DFS recursive backtracker)...")',
            '                g[2*r+1][2*c+1] = " "',
            "                time.sleep(0.18)",
            "            gen(nr, nc)",
            "",
            'draw("Starting...")',
            "time.sleep(0.5)",
            "gen(0, 0)",
            "",
            'g[1][1] = "S"',
            'g[2*ROWS-1][2*COLS-1] = "E"',
            'draw("Maze ready! Running BFS solver...")',
            "time.sleep(1.0)",
            "",
            "q = collections.deque([(1,1)])",
            "cf = {(1,1): None}",
            "end = (2*ROWS-1, 2*COLS-1)",
            "found = False",
            "n = [0]",
            "while q:",
            "    r, c = q.popleft()",
            "    if (r,c) == end: found = True; break",
            "    for dr,dc in [(-1,0),(1,0),(0,-1),(0,1)]:",
            "        nr, nc = r+dr, c+dc",
            '        if 0<=nr<GH and 0<=nc<GW and (nr,nc) not in cf and g[nr][nc]!="#":',
            "            cf[(nr,nc)] = (r,c)",
            "            q.append((nr,nc))",
            '            if g[nr][nc]==" ": g[nr][nc]="."',
            "            n[0] += 1",
            "            if n[0]%4==0:",
            '                draw("BFS solving...  frontier={}".format(len(q)))',
            "                time.sleep(0.14)",
            "if found:",
            "    p = end",
            "    while p and p!=(1,1):",
            "        r, c = p",
            '        if g[r][c] not in ("S","E"): g[r][c]="*"',
            "        p = cf[p]",
            '    draw("Path found!  S=start  E=end  *=path  .=explored")',
        ].join("\n"),
    },
};

class VisualizationManager {
    async prepareVisualization(sessionId, vizId) {
        const viz = VISUALIZATIONS[vizId];
        if (!viz) throw new Error("Visualization not found.");
        const b64 = Buffer.from(viz.code).toString("base64");
        await sessionManager.executeCommand(
            sessionId,
            `echo "${b64}" | base64 -d > ${viz.file}`,
        );
        if (viz.language === "python") {
            return `python3 ./${viz.file}`;
        }
        const compileCmd = `gcc ${viz.file} -o ${vizId}_app`;
        const result = await sessionManager.executeCommand(
            sessionId,
            compileCmd,
        );
        if (result.error)
            throw new Error(`Compilation failed: ${result.error}`);
        return `./${vizId}_app`;
    }
}

module.exports = new VisualizationManager();
